    /* ----------------------------------------------------
       FEEDBACK — a public "message + email + WhatsApp" form (floating button,
       bottom-right, all pages) that writes to a `feedback_log` Supabase table,
       plus an admin panel tab to read/manage what comes in. Follows the exact
       same "table might not exist yet, show the one-time setup SQL" pattern
       already used for home_config, so it degrades the same way everywhere.
    ----------------------------------------------------- */
    let feedbackLog = [];

    function openFeedbackModal() {
      document.getElementById('feedback-modal').classList.remove('hidden');
      document.getElementById('feedback-msg').classList.add('hidden');
      document.getElementById('feedback-message').value = '';
      document.getElementById('feedback-email').value = currentUser?.email || '';
      document.getElementById('feedback-whatsapp').value = '';
      setTimeout(() => document.getElementById('feedback-message').focus(), 50);
    }

    function closeFeedbackModal() {
      document.getElementById('feedback-modal').classList.add('hidden');
    }

    function showFeedbackMsg(text, type = 'error') {
      const el = document.getElementById('feedback-msg');
      const styles = {
        error: 'bg-rose-50 text-rose-800 border-rose-200',
        success: 'bg-emerald-50 text-emerald-800 border-emerald-200'
      };
      el.className = `p-2.5 rounded-lg text-xs border ${styles[type] || styles.error}`;
      el.innerText = text;
      el.classList.remove('hidden');
    }

    async function submitFeedback() {
      const message = document.getElementById('feedback-message').value.trim();
      const email = document.getElementById('feedback-email').value.trim();
      const whatsapp = document.getElementById('feedback-whatsapp').value.trim();
      if (!message) return showFeedbackMsg('Please enter a message before sending.');

      const btn = document.getElementById('feedback-submit-btn');
      const originalText = btn.innerText;
      btn.innerText = 'Sending…';
      btn.disabled = true;

      const row = {
        message,
        email: email || null,
        whatsapp: whatsapp || null,
        page_context: (document.title || '').slice(0, 200),
        status: 'new'
      };

      const { error } = await supabaseClient.from('feedback_log').insert([row]);

      btn.innerText = originalText;
      btn.disabled = false;

      if (error) {
        console.error('Feedback insert failed:', fmtErr(error));
        const msg = String(error.message || error);
        const isMissing = /relation .*feedback_log.* does not exist|table.*feedback_log|Could not find the table/i.test(msg);
        if (isMissing) {
          showFeedbackMsg("This feature isn't fully set up yet on our end — please try again shortly, or reach us another way in the meantime.");
          console.warn(
            "The `feedback_log` table doesn't exist in Supabase yet. One-time setup (SQL Editor → New query):\n\n" +
            "CREATE TABLE IF NOT EXISTS public.feedback_log (\n" +
            "  id bigint generated by default as identity primary key,\n" +
            "  message text NOT NULL,\n" +
            "  email text,\n" +
            "  whatsapp text,\n" +
            "  page_context text,\n" +
            "  status text DEFAULT 'new',\n" +
            "  created_at timestamptz DEFAULT now()\n" +
            ");\n" +
            "ALTER TABLE public.feedback_log ENABLE ROW LEVEL SECURITY;\n" +
            "CREATE POLICY \"feedback_log public insert\" ON public.feedback_log FOR INSERT WITH CHECK (true);\n" +
            "CREATE POLICY \"feedback_log admin read\" ON public.feedback_log FOR SELECT USING (public.is_admin());\n" +
            "CREATE POLICY \"feedback_log admin update\" ON public.feedback_log FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());\n" +
            "CREATE POLICY \"feedback_log admin delete\" ON public.feedback_log FOR DELETE USING (public.is_admin());"
          );
        } else {
          showFeedbackMsg('Could not send right now: ' + msg);
        }
        return;
      }

      showFeedbackMsg("Thanks — your feedback's been sent!", 'success');
      setTimeout(closeFeedbackModal, 1400);
    }

    async function fetchCloudFeedback() {
      const { data, error } = await supabaseClient
        .from('feedback_log')
        .select('*')
        .order('created_at', { ascending: false });
      if (error) {
        console.error('Failed to fetch feedback_log:', fmtErr(error));
        feedbackLog = [];
        return;
      }
      feedbackLog = data || [];
    }

    function renderFeedbackAdmin() {
      const root = document.getElementById('feedback-admin-list');
      if (!root) return;
      root.innerHTML = '<p class="text-slate-400 text-center py-6">Loading…</p>';
      fetchCloudFeedback().then(() => {
        const newCount = feedbackLog.filter(f => f.status === 'new').length;
        const badgeEl = document.getElementById('feedback-nav-badge');
        if (badgeEl) { badgeEl.innerText = newCount; badgeEl.classList.toggle('hidden', !newCount); }

        if (!feedbackLog.length) {
          root.innerHTML = '<p class="text-slate-400 text-center py-6 text-xs">No feedback yet. The form is live on every page (bottom-right "💬 Feedback" button).</p>';
          return;
        }
        root.innerHTML = feedbackLog.map(f => `
          <div class="p-3.5 rounded-xl border ${f.status === 'new' ? 'border-amber-300 bg-amber-50/40' : 'border-slate-200 bg-white'} space-y-1.5">
            <div class="flex items-start justify-between gap-2">
              <p class="text-xs text-slate-800 whitespace-pre-wrap flex-1">${escapeHtml(f.message)}</p>
              ${f.status === 'new' ? '<span class="shrink-0 text-[9px] font-bold uppercase bg-amber-500 text-slate-950 px-1.5 py-0.5 rounded-full">New</span>' : ''}
            </div>
            <div class="flex flex-wrap gap-x-3 gap-y-0.5 text-[10px] text-slate-500">
              <span>${fmtDateTime(f.created_at)}</span>
              ${f.email ? `<a href="mailto:${escapeHtml(f.email)}" class="text-amber-700 hover:underline">✉️ ${escapeHtml(f.email)}</a>` : ''}
              ${f.whatsapp ? `<a href="https://wa.me/${escapeHtml(String(f.whatsapp).replace(/[^\d+]/g, ''))}" target="_blank" rel="noopener" class="text-emerald-700 hover:underline">💬 ${escapeHtml(f.whatsapp)}</a>` : ''}
              ${f.page_context ? `<span class="text-slate-400">from: ${escapeHtml(f.page_context)}</span>` : ''}
            </div>
            <div class="flex gap-2 pt-1">
              ${f.status === 'new'
                ? `<button onclick="markFeedbackRead(${f.id})" class="text-[10px] font-bold text-emerald-700 hover:underline">Mark as read</button>`
                : `<span class="text-[10px] text-slate-400">Read</span>`}
              <button onclick="deleteFeedback(${f.id})" class="text-[10px] font-bold text-rose-600 hover:underline">Delete</button>
            </div>
          </div>
        `).join('');
      });
    }

    async function markFeedbackRead(id) {
      const { error } = await supabaseClient.from('feedback_log').update({ status: 'read' }).eq('id', id);
      if (error) return alert('Could not update: ' + fmtErr(error));
      const item = feedbackLog.find(f => f.id === id);
      if (item) item.status = 'read';
      renderFeedbackAdmin();
    }

    async function deleteFeedback(id) {
      if (!confirm('Delete this feedback entry? This cannot be undone.')) return;
      const { error } = await supabaseClient.from('feedback_log').delete().eq('id', id);
      if (error) return alert('Could not delete: ' + fmtErr(error));
      feedbackLog = feedbackLog.filter(f => f.id !== id);
      renderFeedbackAdmin();
    }

    function renderPaymentOrders() {
      const body = document.getElementById('orders-table-body');
      if (!body) return;
      const filter = document.getElementById('orders-filter').value;
      const q = document.getElementById('orders-search').value.trim().toLowerCase();
      const rows = paymentOrders.filter(o =>
        (filter === 'all' || o.status === filter) &&
        (!q || [o.email, o.title, o.utr, o.name].some(v => (v || '').toLowerCase().includes(q))));
      const pendingCount = paymentOrders.filter(o => o.status === 'pending').length;
      const opt = document.querySelector('#orders-filter option[value="pending"]');
      if (opt) opt.innerText = `Pending (${pendingCount})`;
      [document.getElementById('nav-admin-pending'), ...document.querySelectorAll('.admin-pending-badge')].forEach(badge => {
        if (badge) { badge.innerText = pendingCount; badge.classList.toggle('hidden', !pendingCount); }
      });

      if (!rows.length) {
        body.innerHTML = `<tr><td colspan="7" class="py-6 text-center text-slate-400">${filter === 'pending' ? 'Nothing waiting. New payment claims appear here.' : 'No payments match.'}</td></tr>`;
        return;
      }
      body.innerHTML = rows.map(o => `
        <tr>
          <td class="py-2.5 pr-3 text-slate-500 whitespace-nowrap">${fmtDateTime(o.createdAt)}</td>
          <td class="py-2.5 pr-3"><div class="font-bold text-slate-800">${escapeHtml(o.name || '')}</div><div class="text-slate-500">${escapeHtml(o.email)}</div></td>
          <td class="py-2.5 pr-3">${escapeHtml(o.title)}</td>
          <td class="py-2.5 pr-3 font-mono font-bold">₹${o.amount}</td>
          <td class="py-2.5 pr-3 font-mono">${escapeHtml(o.utr)}${utrDuplicateOrders(o).length ? `<span class="ml-1.5 px-1.5 py-0.5 rounded text-[9px] font-bold bg-rose-100 text-rose-800 whitespace-nowrap" title="This UPI reference also appears on ${utrDuplicateOrders(o).length} other order(s) -- may be reused or guessed rather than genuine">⚠ reused</span>` : ''}</td>
          <td class="py-2.5 pr-3"><span class="px-2 py-0.5 rounded text-[10px] font-bold ${ORDER_STATUS_STYLE[o.status]}">${o.status === 'pending' ? 'Pending' : ORDER_STATUS_LABEL[o.status]}</span>
            ${o.complimentary ? '<span class="ml-1 px-2 py-0.5 rounded text-[10px] font-bold bg-violet-100 text-violet-800">Complimentary</span>' : ''}
            ${o.status === 'rejected' ? `<div class="text-[10px] text-slate-400 mt-0.5">${escapeHtml(o.rejectReason || '')}</div>` : ''}
            ${(+o.refundedAmount || 0) > 0 ? `<div class="text-[10px] text-slate-400 mt-0.5">↩ ₹${o.refundedAmount} refunded${o.status === 'approved' ? ' (partial)' : ''}${o.refundReason ? ` — ${escapeHtml(o.refundReason)}` : ''}</div>` : ''}
            ${o.receiptNo ? `<div class="text-[10px] text-slate-400 mt-0.5">${o.receiptNo}</div>` : ''}
            ${o.adminNote ? `<div class="text-[10px] text-slate-400 mt-0.5" title="Internal note">📝 ${escapeHtml(o.adminNote)}</div>` : ''}</td>
          <td class="py-2.5 text-right whitespace-nowrap">
            ${o.status === 'pending' ? `
              <label class="inline-flex items-center gap-1 mr-2 text-[11px] text-slate-500 font-bold align-middle" title="Waived — no real payment received">
                <input type="checkbox" id="comp-${o.id}" class="align-middle">Comp
              </label>
              <button onclick="approveOrder('${o.id}')" class="px-2.5 py-1 bg-emerald-600 hover:bg-emerald-500 text-white rounded font-bold">Approve</button>
              <button onclick="rejectOrder('${o.id}')" class="px-2.5 py-1 border border-rose-300 text-rose-700 hover:bg-rose-50 rounded font-bold ml-1">Reject</button>`
            : (o.status === 'approved' ? `<button onclick="openReceipt('${o.id}')" class="text-blue-600 font-bold hover:underline">Receipt</button>
              <button onclick="refundOrder('${o.id}')" class="text-rose-600 font-bold hover:underline ml-2">Refund</button>` : '')}
          </td>
        </tr>`).join('');
    }

    function renderMyPayments() {
      const section = document.getElementById('dash-payments-section');
      if (!section) return;
      const student = getCurrentStudent();
      const mine = student ? paymentOrders.filter(o => o.email === student.email) : [];
      section.classList.toggle('hidden', !mine.length);
      document.getElementById('dash-payments-body').innerHTML = mine.map(o => `
        <tr>
          <td class="py-2.5 pr-3 text-slate-500 whitespace-nowrap">${fmtDateTime(o.createdAt)}</td>
          <td class="py-2.5 pr-3 font-bold text-slate-800">${escapeHtml(o.title)}</td>
          <td class="py-2.5 pr-3 font-mono">₹${o.amount}</td>
          <td class="py-2.5 pr-3 font-mono">${escapeHtml(o.utr)}</td>
          <td class="py-2.5 pr-3"><span class="px-2 py-0.5 rounded text-[10px] font-bold ${ORDER_STATUS_STYLE[o.status]}">${ORDER_STATUS_LABEL[o.status]}</span>
            ${o.status === 'rejected' ? `<div class="text-[10px] text-slate-500 mt-0.5">${escapeHtml(o.rejectReason || '')}. Contact the academy if you did pay.</div>` : ''}
            ${(+o.refundedAmount || 0) > 0 ? `<div class="text-[10px] text-slate-500 mt-0.5">₹${o.refundedAmount} refunded${o.status === 'approved' ? ' (partial — access unchanged)' : ''}</div>` : ''}</td>
          <td class="py-2.5 text-right">${o.status === 'approved' ? `<button onclick="openReceipt('${o.id}')" class="text-blue-600 font-bold hover:underline">Receipt</button>` : ''}</td>
        </tr>`).join('');
    }

    function openReceipt(orderId) {
      const o = paymentOrders.find(x => x.id === orderId);
      if (!o || o.status !== 'approved') return;
      if (!isAdmin() && (!currentUser || normalizeEmail(currentUser.email) !== o.email)) return;
      const win = window.open('', '_blank');
      if (!win) return alert('Your browser blocked the receipt tab. Allow pop-ups for this site, then try again.');
      const row = (k, v) => `<tr><td style="padding:8px 0;color:#64748b">${k}</td><td style="padding:8px 0;text-align:right;font-weight:600">${v}</td></tr>`;
      win.document.write(`<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Receipt ${o.receiptNo}</title>
        <style>body{font-family:system-ui,sans-serif;color:#0f172a;max-width:560px;margin:40px auto;padding:0 20px}
        table{width:100%;border-collapse:collapse;font-size:14px} tr{border-bottom:1px solid #e2e8f0}
        .total td{font-size:18px;font-weight:800;border-bottom:0} @media print{button{display:none}}</style></head><body>
        <h1 style="margin:0;font-size:22px">${escapeHtml(pricingMaster.payeeName)}</h1>
        <p style="color:#64748b;margin:4px 0 24px">Payment receipt</p>
        <table>
          ${row('Receipt no.', o.receiptNo)}
          ${row('Payment verified on', fmtDateTime(o.decidedAt))}
          ${row('Student', `${escapeHtml(o.name || '')}<br><span style="font-weight:400;color:#64748b">${escapeHtml(o.email)}</span>`)}
          ${row('Item', escapeHtml(o.title))}
          ${row('Paid by', 'UPI')}
          ${row('UPI reference (UTR)', escapeHtml(o.utr))}
          <tr class="total">${'<td style="padding:14px 0">Amount paid</td><td style="padding:14px 0;text-align:right">₹' + o.amount + '</td>'}</tr>
        </table>
        <p style="color:#94a3b8;font-size:12px;margin-top:24px">This is a payment acknowledgement, not a tax invoice.</p>
        <button onclick="window.print()" style="margin-top:12px;padding:10px 18px;border:0;border-radius:8px;background:#0f172a;color:#fff;font-weight:700;cursor:pointer">Print or save as PDF</button>
        </body></html>`);
      win.document.close();
    }

    // One place to refresh everything that depends on student records or orders
    function afterStudentDataChange() {
      renderPaymentOrders();
      if (currentAdminPanel === 'overview') renderOverview();
      if (currentAdminPanel === 'revenue') renderRevenue();
      renderStudentEntitlementsDesk();
      if (typeof renderStudentDirectoryTable === 'function') renderStudentDirectoryTable();
      if (activeSelectedStudent) {
        const fresh = getStudentRecord(activeSelectedStudent.email);
        if (fresh) selectStudent(fresh);
      }
      refreshUserScopedViews();
    }

    // Manual resync for admins working across multiple tabs/devices. There's no realtime push in
    // this app — each browser only knows what it fetched at load time — so approving a payment on
    // one device won't be visible on another until either a reload or this explicit refresh. This
    // directly addresses "entitlements shown when verifying are different from Access Desk" reports,
    // which happen when two admin sessions are open at once.
    async function refreshStudentDataFromCloud() {
      const btn = document.getElementById('refresh-entitlements-btn');
      const oldText = btn.innerText;
      btn.disabled = true;
      btn.innerText = '🔄 Refreshing…';
      try {
        await fetchCloudStudents();
        await fetchCloudPayments();
        await fetchCloudAllProgress();
        afterStudentDataChange();
        btn.innerText = '✓ Up to date';
      } catch (err) {
        console.error('refreshStudentDataFromCloud failed:', fmtErr(err));
        btn.innerText = '⚠ Refresh failed';
      } finally {
        setTimeout(() => { btn.disabled = false; btn.innerText = oldText; }, 2000);
      }
    }

