-- ============================================================
--  Evolve+ — feedback_log table (idempotent version)
--
--  This is the same one-time setup the app itself prompts for when the
--  feedback_log table is missing (see the in-app error message), rewritten
--  to be safe to run more than once. The original version's CREATE POLICY
--  statements had no IF NOT EXISTS guard (Postgres doesn't support one for
--  policies), so re-running it after a partial success fails with:
--    "policy ... already exists for table feedback_log"
--  This version drops each policy first, so re-running it is always safe.
--
--  Run this once in the Supabase SQL editor. Safe to run more than once.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.feedback_log (
  id bigint generated by default as identity primary key,
  message text NOT NULL,
  email text,
  whatsapp text,
  page_context text,
  status text DEFAULT 'new',
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.feedback_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "feedback_log public insert" ON public.feedback_log;
DROP POLICY IF EXISTS "feedback_log admin read"     ON public.feedback_log;
DROP POLICY IF EXISTS "feedback_log admin update"   ON public.feedback_log;
DROP POLICY IF EXISTS "feedback_log admin delete"   ON public.feedback_log;

CREATE POLICY "feedback_log public insert" ON public.feedback_log FOR INSERT WITH CHECK (true);
CREATE POLICY "feedback_log admin read"    ON public.feedback_log FOR SELECT USING (public.is_admin());
CREATE POLICY "feedback_log admin update"  ON public.feedback_log FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "feedback_log admin delete"  ON public.feedback_log FOR DELETE USING (public.is_admin());

NOTIFY pgrst, 'reload schema';
